name: Install Q CLI on Ubuntu

on:
  # This workflow will run on push events to any branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-q-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (curl, unzip)
        run: sudo apt-get update && sudo apt-get install -y curl unzip

      - name: Download Amazon Q CLI installer
        run: |
          curl --proto '=https' --tlsv1.2 -sSf "https://desktop-release.q.us-east-1.amazonaws.com/latest/q-x86_64-linux.zip" -o "q.zip"

      - name: Unzip installer
        run: unzip q.zip

      - name: Run Q CLI installer
        # The --no-confirm flag is essential for non-interactive environments like a GitHub Action
        run: ./q/install.sh --no-confirm

      - name: Verify Q CLI installation
        run: q --version

      - name: Use Q CLI (example)
        # This step is for demonstration. It will likely fail without authentication.
        # Replace with your specific Q CLI commands.
        run: q chat "Hello from GitHub Actions"
