name: Install Q CLI with IAM Identity Center Login

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-and-run-q:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for assuming a role via OIDC
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1 # Replace with your IAM Identity Center region
          role-session-name: github-action-q-cli
      
      - name: Install dependencies (curl, unzip)
        run: sudo apt-get update && sudo apt-get install -y curl unzip

      - name: Download and install Amazon Q CLI
        run: |
          curl --proto '=https' --tlsv1.2 -sSf "https://desktop-release.q.us-east-1.amazonaws.com/latest/q-x86_64-linux.zip" -o "q.zip"
          unzip q.zip
          ./q/install.sh --no-confirm
      
      - name: Verify Q CLI installation
        run: q --version

      - name: Run authenticated Q CLI command (example)
        # The --no-interactive and --trust-all-tools flags are necessary for CI/CD
        run: q chat --no-interactive --trust-all-tools "What is the AWS CLI?"
